# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JUZ9BBpe-UqcyNC2DmBM_kaLEXDyKu67

Q1
"""

#Q: What is 7.3 plus 5+4j?

7.3 + ( 5 + 4j)

#Q: Are 4e4 and 4E4 same? Check using a python operator
if (4e4 == 4E4):
  print("same")
else:
  print("different")

#Q: if c = 3 + 5j, store it’s real and imaginary parts into r and i variables respectively
c=complex(3,5)
r= c.real
i=c.imag

print(r,i)

#Q: Call the euler’s number e and truncate the decimal part of the number and store that into a variable

import math

e=math.exp(1)

print(e)
i=int(e)
x = e-i

print(x)

"""2.Pass a dictionary into a function and print the elements of the dictionary.

"""

def func(**d):
  print(d)

func(a='1',b='2')

"""3. Print the factorial of a user input number.

"""

a=int(input("Enter a number:"))

b=1
while (a>1):
  b*=a
  a-=1

print(b)

"""4. Print a Fibonacci series upto the given number."""

i = int(input("Enter number of terms: "))

a=0
b=1

if i==1:
  print(a)
elif i==2:
  print(a)
  print(b)
else:

  print(a)
  print(b)
  for _ in range((i-2)):
  
    c=a+b
    a=b
    b=c
    print(c)

"""5. Given an array of integers,find the sum of positive and negative numbers
separately and print "POSITIVE" if sum of positive numbers is greater than the
absolute value of the sum of negative numbers, else print "NEGATIVE".
"""

a= list((input("Enter an array").split(sep=' ')))
pos=0
neg=0
for i in a:
  if int(i)>0:
    pos += int(i)
  else:
    neg += int(i)

if pos > abs(neg):
  print("positive")
elif pos < abs(neg):
  print("negative")
else:
  print("there are equal number of positive and negative terms")

"""6. Given a string, return a string of the same length where the vowels are in the first
and the consonants are in the last. But the inner order of vowels and consonants
should not change.


"""

string = input("enter a string: ")
vowels=''
const=''
for i in range(len(string)):
  if string[i].lower() in ['a','e','i','o','u']:
    vowels += string[i]
  elif string[i]==' ':
    continue
  else:
    const += string[i]

print(vowels+const)

"""7. Write a code which returns the first m multiples of a natural number n, without
using any loop

"""

n=int(input("Enter a number: "))
m=int(input("enter number of multiples: "))

a=range(n,m*n+1,n)
print(*a)

